//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int CashId { get; set; }
        public decimal Amount { get; set; }
        public decimal Margin { get; set; }
        public decimal Withdrawable { get; set; }
        public string AccountCode { get; set; }
        public string LastUpdatedDate { get; set; }
    }
}
