//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAverageCost
    {
        public string Date { get; set; }
        public string Side { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<int> NetVolume { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public int ClientAverageCostID { get; set; }
        public Nullable<decimal> SumOfNetPrice { get; set; }
    }
}
