//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public int LeaderboardId { get; set; }
        public string AccountCode { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<double> PnL { get; set; }
    }
}
