//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchedOrder
    {
        public int MatchedOrderID { get; set; }
        public string UserId { get; set; }
        public string AccountCode { get; set; }
        public Nullable<System.DateTime> OrderDatetime { get; set; }
        public string Side { get; set; }
        public string BoardLot { get; set; }
        public string StockCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MatchDate { get; set; }
    }
}
