//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockXDataBaseEntities : DbContext
    {
        public StockXDataBaseEntities()
            : base("name=StockXDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cash> Cash { get; set; }
        public DbSet<CashHistory> CashHistory { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<ClientAverageCost> ClientAverageCost { get; set; }
        public DbSet<Leaderboard> Leaderboard { get; set; }
        public DbSet<MatchedOrder> MatchedOrder { get; set; }
        public DbSet<Portfolio> Portfolio { get; set; }
        public DbSet<PosCost> PosCost { get; set; }
        public DbSet<Summary> Summary { get; set; }
    }
}
