//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioController
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosCost
    {
        public int PosCostID { get; set; }
        public string AccountCode { get; set; }
        public string StockCode { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
    }
}
